#!/bin/sh

# This script is used to update the filenametags for lookupfile plugin, and the
# ctags & cscope database
# Author  : Easwy Yang
# Homepage: http://easwy.com/
# Date    : Mon Oct 25 16:01:48 CST 2010

# Default project type
PRJ_TYPE=cpp

if [ $# -eq 1 ]; then
	if [ $1 = '-c' ]; then
		rm -f cscope.files cscope.in.out cscope.out cscope.po.out tags
		exit 0
	fi
fi

case ${PRJ_TYPE} in
    java)
    SRC_DIR="."
    find ${SRC_DIR}                         \
                -name "*.java"              \
                > cscope.files
    ;;
    cpp)
    SRC_DIR="."
    find ${SRC_DIR}                         \
                -name "*.h"                 \
                -or -name "*.cpp"           \
                -or -name "*.cc"            \
                -or -name "*.c"             \
                > cscope.files
    ;;
    *)
    ;;
esac

# Generate cscope database & tags
cscope -Rbkq -i cscope.files
ctags --c++-kinds=+p --fields=+iaS --extra=+q -L cscope.files
#ctags --c++-kinds=+p --fields=+iaS --extra=+q -R

exit 0
