#!/bin/bash

if [ "$1" = "" ]; then
    echo -n "Input your target:"
    read TARGET
else
    TARGET="$1"
fi

SERIES="ap121"

case $TARGET in
    12U01)
        ROOT_PATH="mr1xu-dev"
        # refer from Makefile.product
        PREFIX="mr12uv1_cn"
        FLASH_SIZE=4M
        ;;
    12U02)
        #ROOT_PATH="mr12u"
        ROOT_PATH="mr1xu-dev"
        # refer from Makefile.product
        PREFIX="mr12uv2_cn"
        FLASH_SIZE=4M
        ;;
    13U01)
        ROOT_PATH="mr1xu-dev"
        # refer from Makefile.product
        PREFIX="mr13uv1_cn"
        FLASH_SIZE=4M
        ;;
    13U02)
        ROOT_PATH="mr1xu-dev"
        # refer from Makefile.product
        PREFIX="mr13uv2_cn"
        FLASH_SIZE=8M
        ;;
    TR86301)
        ROOT_PATH="tr863"
        PREFIX=tr863v1_cn
        FLASH_SIZE=8M
        ;;
    22U01)
        ROOT_PATH="mr22u"
        PREFIX="mr22uv1_cn"
        FLASH_SIZE=8M
        SERIES="ap143"
        ;;
    iqos_demo)
        ROOT_PATH="mr22u"
        PREFIX="iqos_demo"
        FLASH_SIZE=4M
        SERIES="ap143"
		;;
    tpmini)
        ROOT_PATH="xiaobai"
        PREFIX="tpminiv2_cn"
        FLASH_SIZE=4M
        SERIES="ap143"
        ;;
    sr)
        sudo cp ~/qsdk_cs/qsdk/bin/ar71xx/openwrt-ar71xx-generic-ap151-16M-* /tftpboot/

cat <<EOF
set serverip 192.168.1.100;tftp 80060000 openwrt-ar71xx-generic-ap151-16M-squashfs-sysupgrade.bin;erase 9f050000 +fa0000;cp.b 80060000 9f050000 fa0000;
EOF
#set serverip 192.168.1.100;tftp 80060000 openwrt-ar71xx-generic-ap151-16M-kernel.bin;erase 9fe80000 +170000;cp.b 80060000 9fe80000 170000;tftp 80060000 openwrt-ar71xx-generic-ap151-16M-rootfs-squashfs.bin;erase 9f050000 +e30000;cp.b 80060000 9f050000 e30000;boot
        exit 1
        ;;
    sr_r)
		wget http://mobileci.rd.tp-link.net/jenkins/view/SmartRouter/job/SmartRouter/lastSuccessfulBuild/artifact/qsdk/bin/ar71xx/openwrt-ar71xx-generic-ap151-16M-squashfs-sysupgrade.bin
        sudo mv openwrt-ar71xx-generic-ap151-16M-squashfs-sysupgrade.bin /tftpboot/
		cat <<EOF
set serverip 192.168.1.100;tftp 80060000 openwrt-ar71xx-generic-ap151-16M-squashfs-sysupgrade.bin;erase 9f050000 +fa0000;cp.b 80060000 9f050000 fa0000;
EOF
		exit 1
		;;
    *)
        echo "unknow target:$TARGET"
        exit 1
        ;;
esac

SOURCE_PATH="${HOME}/${ROOT_PATH}/images/${SERIES}"

TIME=`date +%y%m%d`

IMG_NAME="${PREFIX}_3_17_1_up(${TIME}).bin"
#IMG_NAME="${PREFIX}_3_17_1_flash(${TIME}).bin"

TFTP_DIR="/tftpboot"

echo "==============="
echo "sudo cp -f ${SOURCE_PATH}/${IMG_NAME} ${TFTP_DIR}/${IMG_NAME}"
sudo cp -f ${SOURCE_PATH}/${IMG_NAME} ${TFTP_DIR}/${IMG_NAME}

echo "==============="
echo "[flash command]"
if [ ${FLASH_SIZE} = "8M" ]; then
    echo "setenv ipaddr 192.168.1.1;set serverip 192.168.1.100;tftp 80800000 ${IMG_NAME};erase 9f020000 +7c0000;cp.b 80800000 9f020000 7c0000;bootm;"
else
    echo "setenv ipaddr 192.168.1.1;set serverip 192.168.1.100;tftp 80800000 ${IMG_NAME};erase 9f020000 +3c0000;cp.b 80800000 9f020000 3c0000;bootm;"
#    echo "setenv ipaddr 192.168.1.1;set serverip 192.168.1.100;tftp 80800000 ${IMG_NAME};erase 9f000000 +800000;cp.b 80800000 9f000000 800000;tftp 80800000 cal_back.bin;erase 9f7f0000 +10000;cp.b 80800000 9f7f0000 10000;bootm;"
#else
#    echo "setenv ipaddr 192.168.1.1;set serverip 192.168.1.100;tftp 80800000 ${IMG_NAME};erase 9f000000 +400000;cp.b 80800000 9f000000 400000;tftp 80800000 cal_back.bin;erase 9f3f0000 +10000;cp.b 80800000 9f3f0000 10000;bootm;"
#setenv ipaddr 192.168.1.1;set serverip 192.168.1.100;tftp 80800000 up.bin;erase 9f020000 +3c0000;cp.b 80800000 9f020000 3c0000;bootm;
fi
